### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by MethodGrab** [MethodGrab/firefox-custom-new-tab-page#13]
This is a meta ticket to track known issues that currently can't be fixed:

- [ ] #1 Links on the page open in the iframe
- [ ] #11 Limited URL scheme support
- [ ] #12 Site must allow iframing
